export const readiness = [
  {
    code: "BRL", title: "Negocio", level: 5, status: "Modelo en prueba",
    description: "Hay servicios vendidos y precios definidos. Falta comprobar costos completos, margen y repetibilidad de la oferta.",
    evidence: "La producción de shows tiene actividad comercial. El esquema caché + US$50 es una política de precios; su rentabilidad debe contrastarse con liquidaciones completas. Comunicación e institucional requieren su propio presupuesto.",
    next: "Validar precio y margen en tres entregas",
    steps: ["Cerrar 3 servicios pagados con al menos 2 clientes.", "Registrar en los 3: precio, horas, artistas, logística y demás costos; calcular el margen de cada entrega.", "Revisar precios con las devoluciones de los clientes y comprobar margen positivo en el conjunto."],
    proof: "Tres liquidaciones conciliadas y una versión actualizada del modelo de negocio y sus precios.",
  },
  {
    code: "CRL", title: "Cliente", level: 5, status: "Relaciones e interés",
    description: "Hay clientes de shows y vínculos estratégicos. La propuesta comunicacional e institucional necesita validar su valor con ellos.",
    evidence: "Shopping China y Gran Meliá respaldan continuidad comercial en shows. Los vínculos con Not Only Wine y La Cava amplían el campo de colaboración. Esa experiencia no demuestra por sí sola demanda para la futura app.",
    next: "Comprobar el valor con dos clientes piloto",
    steps: ["Acordar con 2 clientes una experiencia comunicacional o institucional y un resultado observable antes de comenzar.", "Realizar ambas experiencias y recoger al menos 5 devoluciones de participantes en cada una.", "Obtener de los 2 clientes una evaluación escrita del resultado y registrar si volverían a contratar y por qué."],
    proof: "Dos casos con objetivo, resultado, diez devoluciones y validación del valor por parte de ambos clientes.",
  },
  {
    code: "TMRL", title: "Equipo", level: 4, status: "Red activa, acuerdos por consolidar",
    description: "20 personas y 10 departamentos según dirección. El núcleo responsable necesita roles, disponibilidad y acuerdos compartidos.",
    evidence: "La nómina informada al 17/09/2026 describe una red de colaboradores, no veinte puestos de dedicación completa. El trabajo conjunto existe; la dedicación y los compromisos deben quedar documentados.",
    next: "Consolidar el núcleo durante cuatro semanas",
    steps: ["Identificar responsables de dirección, producción, tecnología, comunicación y finanzas.", "Dejar aceptados por cada responsable su rol, disponibilidad semanal y forma de tomar decisiones.", "Completar 4 revisiones semanales con todas las tareas críticas asignadas a un responsable y un suplente."],
    proof: "Matriz de roles aceptada y cuatro registros semanales de acuerdos, responsables y entregas.",
    link: { href: "https://www.undertangoclub.com/central", label: "Ver equipo y departamentos" },
  },
  {
    code: "TRL", title: "Tecnología", level: 3, status: "Concepto y funciones en prueba",
    description: "Usamos un panel y herramientas de apoyo. La red operativa móvil y de escritorio sigue siendo un producto por desarrollar y validar.",
    evidence: "Hay funciones de coordinación probadas y herramientas conectadas. Eso no equivale a una app integrada para los distintos roles del universo UnderTango. La estimación se refiere a ese producto en desarrollo.",
    next: "Validar un primer prototipo integrado",
    steps: ["Integrar en un entorno de prueba tres roles: coordinación, artista y cliente, con permisos diferenciados.", "Probar en móvil y escritorio el recorrido crear tarea → asignar → aceptar → cerrar con evidencia.", "Completar 10 recorridos de prueba, conservar los datos al recargar y resolver todos los fallos críticos y accesos no autorizados detectados."],
    proof: "Prototipo demostrable, matriz de permisos y registro de diez pruebas completas con sus resultados.",
    link: { href: "/elitros/sistema-de-herramientas", label: "Ver el sistema de herramientas" },
  },
  {
    code: "IPRL", title: "Propiedad intelectual", level: 2, status: "Activos y derechos por ordenar",
    description: "Existe un antecedente de registro de marca. Falta ordenar titularidad y permisos sobre código, método, materiales e imagen.",
    evidence: "Se revisó el título INPI clase 41, registro 3.456.539, concedido en 2023 a Pablo Guillermo Cieslik. Su vigencia actual y el control sobre el conjunto de activos requieren revisión; la marca sola no resuelve esa estrategia.",
    next: "Documentar los derechos de los activos del piloto",
    steps: ["Inventariar marca, código, método, materiales e imagen utilizados en el primer piloto.", "Identificar para cada activo su titular, licencia o permiso y cualquier autorización faltante.", "Revisar el inventario con asesoramiento especializado y dejar un plan de protección con responsable para cada pendiente."],
    proof: "Inventario completo del piloto y plan revisado de titularidad, permisos y protección.",
  },
  {
    code: "FRL", title: "Financiación", level: 2, status: "Necesidades por dimensionar",
    description: "Hay antecedentes de aportes y actividad comercial. El nuevo ciclo necesita presupuesto, caja conciliada y una estrategia de financiación.",
    evidence: "El fondo anterior tiene registros históricos; el FDG 0.2 está en desarrollo. Esos antecedentes no acreditan financiación disponible para la red operativa ni una nueva ronda cerrada.",
    next: "Definir cuánto hace falta y cómo financiarlo",
    steps: ["Preparar un presupuesto mensual de 12 meses para servicios y primer prototipo, con escenarios mínimo, base y expansión.", "Conciliar el dinero disponible por moneda y separarlo de ingresos esperados, deudas y aportes no recibidos.", "Cuantificar la brecha de financiación e identificar 3 fuentes posibles, con requisitos y una próxima acción para cada una."],
    proof: "Presupuesto de doce meses, saldo conciliado y plan de financiación con importes, fuentes y responsables.",
    link: { href: "https://www.undertangoclub.com/87", label: "Funcionamiento del FDG" },
  },
] as const;
