"use client";
import {useId,useRef,useState} from "react";
import {FRONTS,type Board} from "../../src/lib/panel-model";
import css from "./panel.module.css";
import {dependencyGroups} from "../../src/lib/panel-dependencies";

export type CreateDependency=(name:string,project:string,front:string)=>Promise<string>;
type Props={data:Board;taskId?:string;dependencies:string[];events:string[];disabled:boolean;onChange:(tasks:string[],events:string[])=>void;onBusy:(busy:boolean)=>void;onCreateProject:(name:string)=>Promise<string>;onCreateTask:CreateDependency;onCreateEvent:(name:string)=>Promise<string>};
export default function Dependencies({data,taskId,dependencies,events,disabled,onChange,onBusy,onCreateProject,onCreateTask,onCreateEvent}:Props){
  const uid=useId(),lock=useRef(false);
  const [query,setQuery]=useState(""),[project,setProject]=useState(""),[projectName,setProjectName]=useState(""),[name,setName]=useState(""),[front,setFront]=useState("Primario"),[eventName,setEventName]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
  const [newProjects,setNewProjects]=useState<{id:string;name:string;open:boolean}[]>([]);
  const [newTasks,setNewTasks]=useState<{id:string;name:string;stage:string;projectIds:string[];dependencies:string[]}[]>([]);
  const [newEvents,setNewEvents]=useState<{id:string;name:string;status:string}[]>([]);
  const projects=[...data.projects,...newProjects.filter(p=>!data.projects.some(x=>x.id===p.id))];
  const tasks=[...data.tasks,...newTasks.filter(t=>!data.tasks.some(x=>x.id===t.id))];
  const facts=[...data.events,...newEvents.filter(e=>!data.events.some(x=>x.id===e.id))];
  const needle=query.trim().toLocaleLowerCase();
  async function run(work:()=>Promise<void>){if(disabled||lock.current)return;lock.current=true;onBusy(true);setError("");setMessage("");try{await work();}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar. Revisá antes de reintentar.");}finally{lock.current=false;onBusy(false);}}
  const selectTask=(id:string,checked:boolean)=>onChange(checked?[...new Set([...dependencies,id])]:dependencies.filter(x=>x!==id),events);
  const selectEvent=(id:string,checked:boolean)=>onChange(dependencies,checked?[...new Set([...events,id])]:events.filter(x=>x!==id));
  const groups=dependencyGroups(tasks,projects,taskId,query);
  return <section className={css.waitFields} aria-label="Qué falta para poder empezar"><h3>Qué falta para poder empezar</h3><p className={css.help}>Desplegá un proyecto y marcá sus acciones pendientes. Deben cumplirse todas las condiciones seleccionadas: se habilita esta acción, no el proyecto entero.</p>
    <div aria-live="polite"><strong>Seleccionadas: {dependencies.length+events.length}</strong>{!dependencies.length&&!events.length&&<p className={css.help}>Todavía no seleccionaste ninguna condición.</p>}
    {dependencies.map(id=>{const t=tasks.find(x=>x.id===id);return <p key={id} className={css.help}>{t?.stage==="done"?"✓ Finalizada":t?.stage==="cancelled"?"Descartada — revisar":"Acción pendiente"}: {t?.name||"Acción no disponible"} <button type="button" className={css.linkButton} disabled={disabled} onClick={()=>selectTask(id,false)}>Quitar</button></p>;})}
    {events.map(id=>{const e=facts.find(x=>x.id===id);return <p key={id} className={css.help}>Condición · {e?.status||"Por revisar"}: {e?.name||"Hecho no disponible"} <button type="button" className={css.linkButton} disabled={disabled} onClick={()=>selectEvent(id,false)}>Quitar</button></p>;})}</div>
    <label htmlFor={`${uid}-search`}>Buscar proyecto o acción pendiente</label><input id={`${uid}-search`} value={query} onChange={e=>setQuery(e.target.value)} disabled={disabled}/>
    {groups.map(g=><details key={g.id} open={needle?true:undefined}><summary>{g.name} · {g.items.length} pendientes</summary><fieldset className={css.choices} disabled={disabled}><legend>Acciones de {g.name}</legend><div>{g.items.map(t=><label key={t.id}><input type="checkbox" checked={dependencies.includes(t.id)} onChange={e=>selectTask(t.id,e.target.checked)}/><span>{t.name}</span></label>)}</div></fieldset></details>)}
    {!groups.length&&<p className={css.help}>No hay acciones pendientes que coincidan. Podés crear la que falta abajo.</p>}
    <details><summary>Condiciones externas que estamos esperando</summary><p className={css.help}>Por ejemplo, recibir una aprobación. Se muestran aquí junto con las acciones, sin convertirlas en tareas duplicadas.</p><fieldset className={css.choices} disabled={disabled}><legend>Hechos pendientes</legend><div>{facts.filter(e=>e.status==="Esperando").map(e=><label key={e.id}><input type="checkbox" checked={events.includes(e.id)} onChange={x=>selectEvent(e.id,x.target.checked)}/><span>{e.name}</span></label>)}</div></fieldset><label htmlFor={`${uid}-fact`}>Nueva condición externa</label><input id={`${uid}-fact`} maxLength={250} value={eventName} disabled={disabled} onChange={e=>setEventName(e.target.value)}/><button type="button" className={css.button} disabled={disabled||!eventName.trim()} onClick={()=>run(async()=>{const title=eventName.trim(),id=await onCreateEvent(title);setNewEvents(old=>[...old,{id,name:title,status:"Esperando"}]);selectEvent(id,true);setEventName("");setMessage("Condición creada y seleccionada. Guardá la acción para confirmar el vínculo.");})}>Crear condición y seleccionarla</button></details>
    <details><summary>¿Falta una acción? Crear aquí</summary><p className={css.help}>Elegí un proyecto existente o creá uno. Después podés agregar una o varias acciones, de a una. Cada creación se guarda; cancelar este formulario no las elimina.</p><label htmlFor={`${uid}-project`}>Proyecto de la nueva acción</label><select id={`${uid}-project`} value={project} disabled={disabled} onChange={e=>setProject(e.target.value)}><option value="">Elegí un proyecto</option>{projects.filter(p=>p.open).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
    <label htmlFor={`${uid}-project-name`}>O crear un proyecto nuevo</label><input id={`${uid}-project-name`} maxLength={250} value={projectName} disabled={disabled} onChange={e=>setProjectName(e.target.value)}/><button type="button" className={css.button} disabled={disabled||!projectName.trim()} onClick={()=>run(async()=>{const title=projectName.trim(),id=await onCreateProject(title);setNewProjects(old=>[...old,{id,name:title,open:true}]);setProject(id);setProjectName("");setMessage("Proyecto creado. Ahora agregá su primera acción abajo.");})}>Crear proyecto y elegirlo</button>
    <label htmlFor={`${uid}-name`}>Acción concreta que falta</label><input id={`${uid}-name`} maxLength={250} value={name} disabled={disabled} onChange={e=>setName(e.target.value)}/><label htmlFor={`${uid}-front`}>Frente de la nueva acción</label><select id={`${uid}-front`} value={front} disabled={disabled} onChange={e=>setFront(e.target.value)}>{FRONTS.map(f=><option key={f}>{f}</option>)}</select><p className={css.help}>Queda como Acción inmediata, al final del frente elegido, con Pablo Cieslik como responsable. Podés editarla después.</p><button type="button" className={css.button} disabled={disabled||!project||!name.trim()} onClick={()=>run(async()=>{const title=name.trim(),id=await onCreateTask(title,project,front);setNewTasks(old=>[...old,{id,name:title,stage:"ready",projectIds:[project],dependencies:[]}]);selectTask(id,true);setName("");setMessage("Acción creada y seleccionada. Podés agregar otra; guardá la acción original para confirmar sus dependencias.");})}>Crear acción y seleccionarla</button></details>
    <p className={css.help}>Los tildes son un borrador hasta pulsar Guardar. Finalizar las acciones vinculadas libera automáticamente esta acción cuando no queda otra condición pendiente.</p>{message&&<p role="status" className={css.help}>{message}</p>}{error&&<p role="alert" className={css.error}>{error}</p>}
  </section>;
}
