"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { supabase } from "../../src/lib/supabase";
import { BASE, TABLES, type Board, type Stage } from "../../src/lib/panel-model";
import css from "./panel.module.css";
type Data=Board&{revisions:Record<string,string>};
type Task=Board["tasks"][number];
type Editor={kind:"task"|"project"|"event";id?:string;revision?:string;initial:Record<string,any>};
const labels:Record<Stage,string>={ready:"Disponible",doing:"En curso",waiting:"En espera",catalog:"Por catalogar",done:"Finalizada",cancelled:"Descartada"};
function safeDoc(v:string){try{const u=new URL(v);return u.protocol==="https:"&&["docs.google.com","drive.google.com"].includes(u.hostname)?v:undefined;}catch{return undefined;}}
function date(v:string){return v?new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString("es-AR",{day:"numeric",month:"short"}):"Sin fecha";}
async function api(path="",body?:unknown){
  const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Ingresá para abrir el panel.");
  const r=await fetch(`/api/panel${path}`,{method:body?"POST":"GET",headers:{Authorization:`Bearer ${session.access_token}`,...(body?{"Content-Type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:"no-store"});
  const v=await r.json();if(!r.ok)throw new Error(v.error||"No se pudo completar la operación.");return v;
}
function Choices({label,options,value,onChange}:{label:string;options:{id:string;name:string}[];value:string[];onChange:(v:string[])=>void}){
  const [query,setQuery]=useState("");
  const filtered=options.filter(o=>value.includes(o.id)||o.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>Number(value.includes(b.id))-Number(value.includes(a.id))).slice(0,60);
  return <fieldset className={css.choices}><legend>{label}</legend><input aria-label={`Buscar ${label.toLowerCase()}`} placeholder="Buscar para vincular…" value={query} onChange={e=>setQuery(e.target.value)}/><div>{filtered.map(o=><label key={o.id}><input type="checkbox" checked={value.includes(o.id)} onChange={e=>onChange(e.target.checked?[...value,o.id]:value.filter(x=>x!==o.id))}/><span>{o.name}</span></label>)}{!filtered.length&&<p className={css.muted}>Sin coincidencias.</p>}</div>{options.length>60&&<p className={css.muted}>Buscá por nombre para encontrar más registros.</p>}</fieldset>;
}
function Modal({children,onClose,busy}:{children:ReactNode;onClose:()=>void;busy:boolean}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const d=ref.current;d?.showModal();const old=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{d?.close();document.body.style.overflow=old;};},[]);
  return <dialog ref={ref} className={css.dialog} aria-labelledby="editor-heading" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}>{children}</dialog>;
}
export default function Panel(){
  const [sessionEmail,setSessionEmail]=useState<string|null>(null),[authLoading,setAuthLoading]=useState(true);
  const [email,setEmail]=useState("pablocieslik@gmail.com"),[password,setPassword]=useState("");
  const [data,setData]=useState<Data>(),[busy,setBusy]=useState(false),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [tab,setTab]=useState("fronts"),[search,setSearch]=useState(""),[limit,setLimit]=useState(36),[editor,setEditor]=useState<Editor>();
  const refreshRef=useRef(false),sessionRef=useRef<string|null>(null);
  useEffect(()=>{
    supabase.auth.getSession().then(({data})=>{setSessionEmail(data.session?.user.email||null);sessionRef.current=data.session?.user.email||null;setAuthLoading(false);});
    const {data}=supabase.auth.onAuthStateChange((_event,session)=>{sessionRef.current=session?.user.email||null;setSessionEmail(sessionRef.current);if(!session){setData(undefined);setEditor(undefined);}setAuthLoading(false);});
    return()=>data.subscription.unsubscribe();
  },[]);
  const refresh=useCallback(async(fresh=false)=>{
    if(refreshRef.current)return;refreshRef.current=true;setRefreshing(true);
    try{const value=await api(fresh?"?refresh=1":"");if(sessionRef.current){setData(value);setError("");}}
    catch(e){setError(e instanceof Error?e.message:"No se pudo actualizar.");throw e;}
    finally{refreshRef.current=false;setRefreshing(false);}
  },[]);
  useEffect(()=>{if(sessionEmail)refresh().catch(()=>{});},[sessionEmail,refresh]);
  useEffect(()=>{
    if(!sessionEmail||editor)return;
    const update=()=>{if(document.visibilityState==="visible")refresh().catch(()=>{});};
    const timer=setInterval(update,120000);document.addEventListener("visibilitychange",update);window.addEventListener("online",update);
    return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",update);window.removeEventListener("online",update);};
  },[sessionEmail,editor,refresh]);
  useEffect(()=>setLimit(36),[tab,search]);
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;setPassword("");}catch{setError("No se pudo ingresar. Revisá el correo y la contraseña del sitio.");}finally{setBusy(false);}}
  function editTask(t:Task,next?:Stage){setEditor({kind:"task",id:t.id,revision:data!.revisions[t.id],initial:{name:t.name,owner:t.owner,priority:t.priority||"Media",due:t.due,stage:next||t.stage,reason:t.reason,doc:t.doc,order:t.order,projects:t.directProjectIds,cases:t.caseIds,dependencies:t.dependencies,events:t.eventIds,...(next?{_previousStage:t.stage}:{})}});}
  function newTask(project?:string){setEditor({kind:"task",initial:{name:"",owner:"Pablo Cieslik",priority:"Media",due:"",stage:project?"ready":"catalog",reason:"",doc:"",order:0,projects:project?[project]:[],cases:[],dependencies:[],events:[]}});}
  function editProject(id:string){const p=data!.projects.find(p=>p.id===id)!;setEditor({kind:"project",id,revision:data!.revisions[id],initial:{front:p.front,rank:p.rank===9999?1:p.rank,status:p.status,doc:p.doc}});}
  function editEvent(id?:string){const e=data?.events.find(e=>e.id===id);setEditor({kind:"event",id,revision:id?data!.revisions[id]:undefined,initial:e?{name:e.name,type:e.type,status:e.status,evidence:e.evidence}:{name:"",type:"Respuesta",status:"Esperando",evidence:""}});}
  async function save(changes:Record<string,any>){
    setBusy(true);setError("");try{await api("",{kind:editor!.kind,id:editor!.id,revision:editor!.revision,changes});setEditor(undefined);setNotice("Cambio guardado y confirmado en Airtable.");try{await refresh(true);}catch{setNotice("El cambio se guardó. Falta actualizar la vista; pulsá Actualizar.");}}finally{setBusy(false);}
  }
  const matches=(name:string)=>name.toLocaleLowerCase().includes(search.toLocaleLowerCase());
  const taskCard=(t:Task)=><article key={t.id} className={css.card}><div className={css.projectName}>{data!.projects.filter(p=>t.projectIds.includes(p.id)).map(p=>`${p.name} · ${p.open?p.front+" "+(p.rank===9999?"—":p.rank):"cerrado"}`).join(" / ")||"Sin proyecto"}</div><h3>{t.name}</h3><span className={`${css.badge} ${["waiting","catalog"].includes(t.stage)?css.warning:""}`}>{labels[t.stage]}</span>{t.released&&<p className={css.muted}>Dependencias resueltas · lista para continuar</p>}{!!t.issues.length&&<ul className={css.smallList}>{t.issues.map((s,i)=><li key={i}>{s}</li>)}</ul>}{!!t.blockers.length&&<p className={css.help}>Espera: {t.blockers.join("; ")}</p>}<div className={css.meta}><span>{t.owner||"Sin responsable"}</span><span>{t.priority}</span><span>{date(t.due)}</span>{t.order>0&&<span>Paso {t.order}</span>}</div><div className={css.actions}><button className={css.button} disabled={busy||!!error} onClick={()=>editTask(t)}>Abrir / editar</button>{t.stage==="ready"&&<button className={css.primary} disabled={busy||!!error} onClick={()=>editTask(t,"doing")}>Empezar</button>}{t.stage==="doing"&&<button className={css.primary} disabled={busy||!!error} onClick={()=>editTask(t,"done")}>Finalizar</button>}{safeDoc(t.doc)&&<a href={safeDoc(t.doc)} target="_blank" rel="noreferrer">Documento ↗</a>}</div></article>;
  if(authLoading)return <main className={css.panel}><div className={css.login}>Verificando acceso…</div></main>;
  if(!sessionEmail)return <main className={css.panel}><div className={`${css.card} ${css.login}`}><span className={css.brand}>Ø UnderTango · privado</span><h1>Panel de control</h1><p>Frentes, acciones y próximos pasos en un solo lugar.</p><form onSubmit={login}><label htmlFor="email">Correo</label><input id="email" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="password">Contraseña del sitio</label><input id="password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/><button className={css.primary} disabled={busy}>{busy?"Ingresando…":"Ingresar al panel"}</button></form>{error&&<p className={css.error} role="alert">{error}</p>}<p className={css.help}>Acceso reservado a la cuenta habilitada por Pablo. Usá la misma cuenta de UnderTango.</p><a href="/">Volver al sitio</a></div></main>;
  const counts=(stage:Stage)=>data?.tasks.filter(t=>t.stage===stage).length||0;
  const filtered=data?.tasks.filter(t=>(tab==="all"?!["done","cancelled"].includes(t.stage):tab==="history"?["done","cancelled"].includes(t.stage):t.stage===tab)&&matches([t.name,t.owner,...data.projects.filter(p=>t.projectIds.includes(p.id)).map(p=>p.name)].join(" ")))||[];
  return <main className={css.panel}><header className={css.top}><div><span className={css.brand}>Ø UnderTango · operación</span><h1>Panel de control</h1><div className={css.muted}>{data?`Airtable · última lectura ${new Date(data.updatedAt).toLocaleTimeString("es-AR",{timeZone:"America/Argentina/Cordoba",hour:"2-digit",minute:"2-digit"})}`:"Conectando con Airtable…"}</div></div><div className={css.actions}><button className={css.button} disabled={refreshing||busy} onClick={()=>refresh(true).catch(()=>{})}>{refreshing?"Actualizando…":"Actualizar"}</button><button className={css.primary} disabled={!data||busy||!!error} onClick={()=>newTask()}>+ Capturar acción</button><button className={css.linkButton} onClick={()=>supabase.auth.signOut()}>Salir</button></div></header>
    {error&&<div className={css.error} role="alert">{error}{data&&<div>La información visible corresponde a la última lectura. Actualizá para seguir editando.</div>}</div>}{notice&&<div className={css.notice} role="status">{notice}<button className={css.linkButton} onClick={()=>setNotice("")}>Cerrar aviso</button></div>}
    {data?<><nav className={css.tabs} aria-label="Vistas del panel">{[["fronts","Frentes",data.fronts.reduce((n,f)=>n+f.tasks.length,0)],["doing","En curso",counts("doing")],["waiting","En espera",counts("waiting")],["catalog","Por catalogar",counts("catalog")+data.projectIssues.length],["all","Todas las acciones",data.tasks.filter(t=>!["done","cancelled"].includes(t.stage)).length],["projects","Proyectos",data.projects.filter(p=>p.open).length],["events","Disparadores",data.events.length],["history","Historial",counts("done")+counts("cancelled")]].map(([key,label,count])=><button key={key} className={`${css.tab} ${tab===key?css.active:""}`} aria-current={tab===key?"page":undefined} onClick={()=>setTab(String(key))}>{label}<span className={css.count}>{count}</span></button>)}</nav>
    {tab==="fronts"?<><p className={css.help}>Hasta tres acciones disponibles por frente, según el ranking guardado. La cola completa queda en Todas las acciones. Se actualiza cada dos minutos mientras esta página está visible.</p><div className={css.fronts}>{data.fronts.map(front=><section key={front.name} className={css.front}><h2>{front.name}</h2><p className={css.muted}>{front.tasks.length} de 3 plazas</p>{front.tasks.length?front.tasks.map(id=>taskCard(data.tasks.find(t=>t.id===id)!)):<div className={css.empty}><strong>Sin acciones disponibles</strong>Revisá los próximos pasos o las dependencias de este frente.</div>}</section>)}</div></>:<><div className={css.toolbar}><input className={css.search} aria-label="Buscar en esta vista" placeholder="Buscar por acción, proyecto o responsable…" value={search} onChange={e=>setSearch(e.target.value)}/>{tab==="events"&&<button className={css.primary} disabled={!!error} onClick={()=>editEvent()}>+ Registrar lo que espero</button>}</div>
    {tab==="projects"?<>{data.projects.filter(p=>p.open&&matches(p.name)).sort((a,b)=>a.front.localeCompare(b.front)||a.rank-b.rank).map(p=><article className={css.projectRow} key={p.id}><div><span className={css.muted}>{p.front} · posición {p.rank===9999?"sin definir":p.rank}</span><h3>{p.name}</h3><p className={css.help}>{data.tasks.filter(t=>t.projectIds.includes(p.id)&&!["done","cancelled"].includes(t.stage)).length} acciones abiertas · {p.status}</p></div><div className={css.actions}><button className={css.button} disabled={!!error} onClick={()=>editProject(p.id)}>Editar proyecto</button><button className={css.button} disabled={!!error} onClick={()=>newTask(p.id)}>+ Próximo paso</button>{safeDoc(p.doc)&&<a href={safeDoc(p.doc)} target="_blank" rel="noreferrer">Documento ↗</a>}</div></article>)}</>:tab==="events"?<div className={css.list}>{data.events.filter(e=>matches(e.name)).map(e=><article className={css.card} key={e.id}><span className={css.badge}>{e.status} · {e.type}</span><h3>{e.name}</h3><p className={css.help}>{data.tasks.filter(t=>t.eventIds.includes(e.id)&&!["done","cancelled"].includes(t.stage)).length} acciones vinculadas</p>{e.evidence&&<p>{e.evidence}</p>}<button className={css.button} disabled={!!error} onClick={()=>editEvent(e.id)}>Abrir / confirmar hecho</button></article>)}{!data.events.length&&<div className={css.empty}>Todavía no hay hechos registrados.</div>}</div>:<>
    {tab==="catalog"&&<><p className={css.help}>Cada registro explica qué falta. Definilo, vinculalo o descartalo con un motivo. Los proyectos sin próximo paso también aparecen aquí.</p>{data.projectIssues.filter(item=>matches(data.projects.find(p=>p.id===item.id)!.name)).map(item=>{const p=data.projects.find(p=>p.id===item.id)!;return <article className={css.projectRow} key={item.id}><div><span className={css.badge}>Proyecto por revisar</span><h3>{p.name}</h3><p className={css.help}>{item.reasons.join(" · ")}</p></div><div className={css.actions}><button className={css.button} disabled={!!error} onClick={()=>editProject(p.id)}>Revisar proyecto</button><button className={css.button} disabled={!!error} onClick={()=>newTask(p.id)}>Definir próximo paso</button></div></article>;})}<h2 className={css.sectionTitle}>Acciones por catalogar</h2></>}
    <div className={css.list}>{filtered.slice(0,limit).map(taskCard)}</div>{!filtered.length&&<div className={css.empty}>No hay acciones que coincidan con esta vista y búsqueda.</div>}{filtered.length>limit&&<div className={css.pagination}><button className={css.button} onClick={()=>setLimit(n=>n+36)}>Mostrar más ({filtered.length-limit} restantes)</button></div>}</>}</>}
    </>:!error&&<div className={css.empty}>Leyendo los frentes y sus acciones…</div>}
    {editor&&data&&<EditForm key={`${editor.kind}-${editor.id||"new"}`} editor={editor} data={data} busy={busy} onClose={()=>setEditor(undefined)} onSave={save}/>}
  </main>;
}
function EditForm({editor,data,busy,onClose,onSave}:{editor:Editor;data:Data;busy:boolean;onClose:()=>void;onSave:(changes:Record<string,any>)=>Promise<void>}){
  const [value,setValue]=useState(editor.initial),[error,setError]=useState("");const set=(key:string,v:any)=>setValue(old=>({...old,[key]:v}));
  async function submit(e:FormEvent){e.preventDefault();setError("");const change=Object.fromEntries(Object.entries(value).filter(([k,v])=>!k.startsWith("_")&&(!editor.id||JSON.stringify(v)!==JSON.stringify(editor.initial[k]))));if(editor.initial._previousStage)change.stage=value.stage;try{await onSave(change);}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar.");}}
  const task=editor.kind==="task"?data.tasks.find(t=>t.id===editor.id):undefined;
  const input=(key:string,label:string,type="text",max=250)=><div><label htmlFor={`edit-${key}`}>{label}</label><input id={`edit-${key}`} type={type} maxLength={max} value={value[key]??""} onChange={e=>set(key,type==="number"?Number(e.target.value):e.target.value)}/></div>;
  const select=(key:string,label:string,options:string[])=><div><label htmlFor={`edit-${key}`}>{label}</label><select id={`edit-${key}`} value={value[key]} onChange={e=>set(key,e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></div>;
  const area=(key:string,label:string,required=false)=><div><label htmlFor={`edit-${key}`}>{label}</label><textarea id={`edit-${key}`} required={required} maxLength={key==="reason"?1000:1500} value={value[key]||""} onChange={e=>set(key,e.target.value)}/></div>;
  return <Modal onClose={onClose} busy={busy}><div className={css.actions}><span className={css.brand}>{editor.kind==="task"?"Acción":editor.kind==="project"?"Proyecto":"Hecho esperado"}</span><button className={css.linkButton} disabled={busy} onClick={onClose}>Cerrar</button></div><h2 id="editor-heading">{editor.id?editor.kind==="project"?data.projects.find(p=>p.id===editor.id)?.name:value.name:editor.kind==="task"?"Capturar próximo paso":"Registrar lo que espero"}</h2><form onSubmit={submit}>
    {editor.kind!=="project"&&input("name",editor.kind==="task"?"Acción concreta":"Hecho que debe ocurrir")}
    {editor.kind==="task"&&<><label htmlFor="edit-stage">Estado de la acción</label><select id="edit-stage" value={value.stage} onChange={e=>set("stage",e.target.value)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{task?.description&&<details><summary>Descripción registrada</summary><p className={css.help}>{task.description}</p></details>}<div className={css.two}>{input("owner","Responsable")}{input("due","Vencimiento","date")}</div><div className={css.two}>{select("priority","Prioridad",["Alta","Media","Baja"])}{input("order","Paso en el plan","number")}</div>
    {["waiting","catalog"].includes(value.stage)&&area("reason","Qué falta o por qué espera")}{["done","cancelled"].includes(value.stage)&&area("evidence",value.stage==="done"?"Resultado que confirma el cierre":"Motivo del descarte",true)}
    <Choices label="Proyectos vinculados" options={data.projects.map(p=>({id:p.id,name:p.name+(p.open?"":" · cerrado")}))} value={value.projects} onChange={v=>set("projects",v)}/>
    <details open={value.stage==="waiting"}><summary>Dependencias y hechos esperados</summary><p className={css.help}>Todas las dependencias deben estar resueltas. Una explicación sola no habilita En espera. Registrá hechos externos en Disparadores y luego vinculalos aquí.</p><Choices label="Depende de acciones" options={data.tasks.filter(t=>t.id!==editor.id&&t.stage!=="cancelled").map(t=>({id:t.id,name:`${labels[t.stage]} · ${t.name}`}))} value={value.dependencies} onChange={v=>set("dependencies",v)}/><Choices label="Eventos disparadores" options={data.events.map(e=>({id:e.id,name:`${e.status} · ${e.name}`}))} value={value.events} onChange={v=>set("events",v)}/></details>
    <details><summary>Caso relacionado</summary><Choices label="Casos vinculados" options={data.cases} value={value.cases} onChange={v=>set("cases",v)}/></details></>}
    {editor.kind==="project"&&<><p className={css.help}>La acción actual se obtiene de Seguimientos. Para cerrar el proyecto, resolvé o reasigná sus acciones abiertas.</p><div className={css.two}>{select("front","Frente",["Primario","Secundario","Terciario"])}{input("rank","Posición en el frente","number")}</div>{select("status","Estado del proyecto",["Activo","En espera","Completado","Archivado"])}</>}
    {editor.kind==="event"&&<>{select("type","Tipo de hecho",["Material","Respuesta","Pago","Fecha","Aprobación","Entrega","Disponibilidad","Otro"])}{select("status","Estado del hecho",["Esperando","Ocurrido","Descartado"])}{area("evidence","Evidencia / contexto",value.status==="Ocurrido")}<p className={css.help}>Marcar Ocurrido habilita las acciones vinculadas sin otras dependencias. Una fecha de revisión no demuestra que llegó una respuesta o un pago.</p></>}
    {editor.kind!=="event"&&input("doc","Documento de apoyo en Drive / Docs","url",1000)}
    {editor.id&&<p><a href={`https://airtable.com/${BASE}/${TABLES[editor.kind==="task"?"tasks":editor.kind==="project"?"projects":"events"]}/${editor.id}`} target="_blank" rel="noreferrer">Abrir registro completo en Airtable ↗</a></p>}{error&&<p className={css.error} role="alert">{error}</p>}<footer><button type="button" className={css.button} disabled={busy} onClick={onClose}>Cancelar</button><button className={css.primary} disabled={busy}>{busy?"Guardando y verificando…":"Guardar en Airtable"}</button></footer></form></Modal>;
}
