"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { BASE, TABLES, FRONTS, frontPosition, projectActionSummary, type Board, type Stage } from "../../src/lib/panel-model";
import css from "./panel.module.css";
type Data=Board&{revisions:Record<string,string>;actor:string};
type Task=Board["tasks"][number];
type Editor={kind:"task"|"project"|"event";id?:string;revision?:string;mode?:"position"|"status";initial:Record<string,any>};
const labels:Record<Stage,string>={ready:"Acción inmediata",recurring:"Acción recurrente",doing:"En curso",waiting:"En espera",catalog:"Por catalogar",done:"Finalizada",cancelled:"Descartada"};
function safeDoc(v:string){try{const u=new URL(v);return u.protocol==="https:"&&["docs.google.com","drive.google.com"].includes(u.hostname)?v:undefined;}catch{return undefined;}}
function date(v:string){return v?new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString("es-AR",{day:"numeric",month:"short"}):"Sin fecha";}
class ApiError extends Error { constructor(message:string,public status:number){super(message);} }
async function api(path="",body?:unknown){
  const r=await fetch(`/api/panel${path}`,{method:body?"POST":"GET",credentials:"same-origin",headers:body?{"Content-Type":"application/json"}:{},...(body?{body:JSON.stringify(body)}:{}),cache:"no-store"});
  const v=await r.json();if(!r.ok)throw new ApiError(v.error||"No se pudo completar la operación.",r.status);return v;
}
function Choices({label,options,value,onChange}:{label:string;options:{id:string;name:string}[];value:string[];onChange:(v:string[])=>void}){
  const [query,setQuery]=useState("");
  const filtered=options.filter(o=>value.includes(o.id)||o.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>Number(value.includes(b.id))-Number(value.includes(a.id))).slice(0,60);
  return <fieldset className={css.choices}><legend>{label}</legend><input aria-label={`Buscar ${label.toLowerCase()}`} placeholder="Buscar para vincular…" value={query} onChange={e=>setQuery(e.target.value)}/><div>{filtered.map(o=><label key={o.id}><input type="checkbox" checked={value.includes(o.id)} onChange={e=>onChange(e.target.checked?[...value,o.id]:value.filter(x=>x!==o.id))}/><span>{o.name}</span></label>)}{!filtered.length&&<p className={css.muted}>Sin coincidencias.</p>}</div>{options.length>60&&<p className={css.muted}>Buscá por nombre para encontrar más registros.</p>}</fieldset>;
}
function Modal({children,onClose,busy,compact=false}:{children:ReactNode;onClose:()=>void;busy:boolean;compact?:boolean}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const d=ref.current;d?.showModal();const old=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{d?.close();document.body.style.overflow=old;};},[]);
  return <dialog ref={ref} className={`${css.dialog} ${compact?css.quickDialog:""}`} aria-labelledby="editor-heading" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}>{children}</dialog>;
}
export default function Panel(){
  const [sessionEmail,setSessionEmail]=useState<string|null>(null),[authLoading,setAuthLoading]=useState(true);
  const [data,setData]=useState<Data>(),[busy,setBusy]=useState(false),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [tab,setTab]=useState("fronts"),[search,setSearch]=useState(""),[limit,setLimit]=useState(36),[editor,setEditor]=useState<Editor>();
  const [projectFront,setProjectFront]=useState(""),[taskProject,setTaskProject]=useState("");
  const refreshRef=useRef(false);
  const refresh=useCallback(async(fresh=false)=>{
    if(refreshRef.current)return;refreshRef.current=true;setRefreshing(true);
    try{const value=await api(fresh?"?refresh=1":"");setSessionEmail(value.actor);setData(value);setError("");}
    catch(e){if(e instanceof ApiError&&[401,403].includes(e.status)){setSessionEmail(null);setData(undefined);setEditor(undefined);setError("Este navegador todavía no está habilitado para el panel.");}else{setError(e instanceof ApiError?e.message:"No se pudo conectar. Revisá tu conexión y volvé a intentar.");}throw e;}
    finally{refreshRef.current=false;setRefreshing(false);setAuthLoading(false);}
  },[]);
  useEffect(()=>{refresh().catch(()=>{});},[refresh]);
  useEffect(()=>{
    if(!sessionEmail||editor)return;
    const update=()=>{if(document.visibilityState==="visible")refresh().catch(()=>{});};
    const timer=setInterval(update,120000);document.addEventListener("visibilitychange",update);window.addEventListener("online",update);
    return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",update);window.removeEventListener("online",update);};
  },[sessionEmail,editor,refresh]);
  useEffect(()=>setLimit(36),[tab,search]);
  function openRanking(front:string){setProjectFront(front);setSearch("");setTab("projects");}
  function openProjectTasks(projectId:string){setTaskProject(projectId);setSearch("");setTab("all");}
  function editTask(t:Task,next?:Stage,quick=false){setEditor({kind:"task",id:t.id,revision:data!.revisions[t.id],mode:quick?"status":undefined,initial:{name:t.name,owner:t.owner,priority:t.priority||"Media",due:t.due,stage:next||t.stage,reason:t.reason,doc:t.doc,order:t.order,projects:t.directProjectIds,cases:t.caseIds,dependencies:t.dependencies,events:t.eventIds,...(next?{_previousStage:t.stage}:{})}});}
  function newTask(project?:string){setEditor({kind:"task",initial:{name:"",owner:"Pablo Cieslik",priority:"Media",due:"",stage:project?"ready":"catalog",reason:"",doc:"",order:0,projects:project?[project]:[],cases:[],dependencies:[],events:[]}});}
  function editProject(id:string,quick=false){const p=data!.projects.find(p=>p.id===id)!;setEditor({kind:"project",id,revision:data!.revisions[id],mode:quick?"position":undefined,initial:{front:p.front,rank:p.rank===9999?1:p.rank,status:p.status,doc:p.doc}});}
  function editEvent(id?:string){const e=data?.events.find(e=>e.id===id);setEditor({kind:"event",id,revision:id?data!.revisions[id]:undefined,initial:e?{name:e.name,type:e.type,status:e.status,evidence:e.evidence}:{name:"",type:"Respuesta",status:"Esperando",evidence:""}});}
  async function save(changes:Record<string,any>){
    setBusy(true);setError("");try{await api("",{kind:editor!.kind,id:editor!.id,revision:editor!.revision,changes});setEditor(undefined);setNotice("Cambio guardado y confirmado en Airtable.");try{await refresh(true);}catch{setNotice("El cambio se guardó. Falta actualizar la vista; pulsá Actualizar.");}}finally{setBusy(false);}
  }
  async function createWaitEvent(name:string){
    const result=await api("",{kind:"event",changes:{name,type:"Otro",status:"Esperando",evidence:"Hecho registrado desde el cambio de estado de una acción."}});
    await refresh(true);
    return result.id as string;
  }
  const matches=(name:string)=>name.toLocaleLowerCase().includes(search.toLocaleLowerCase());
  const taskCard=(t:Task)=><article key={t.id} className={css.card} aria-label={t.name}>
    <div className={css.cardProjects}>{data!.projects.filter(p=>t.projectIds.includes(p.id)).map(p=><div key={p.id} className={css.cardProject}>
      <div className={css.projectName}><strong>Proyecto</strong><span>{p.name}</span></div>
      {p.open?<button className={css.positionButton} disabled={busy||!!error||refreshing} onClick={()=>editProject(p.id,true)} aria-label={`Frente y posición de ${p.name}`}><strong>{frontPosition(p.front,p.rank)}</strong><span>Frente y posición</span></button>:<span className={css.badge}>Proyecto cerrado</span>}
    </div>)}</div>
    {!t.projectIds.length&&<div className={css.projectName}>Sin proyecto</div>}
    <div className={css.actionLabel}>Acción</div><h3>{t.name}</h3><div className={css.statusRow}><span className={`${css.badge} ${["waiting","catalog"].includes(t.stage)?css.warning:""}`}>{labels[t.stage]}</span><button className={css.button} disabled={busy||!!error||refreshing} onClick={()=>editTask(t,undefined,true)}>Cambiar estado</button></div>
    {t.released&&<p className={css.muted}>Dependencias resueltas · lista para continuar</p>}{!!t.issues.length&&<ul className={css.smallList}>{t.issues.map((s,i)=><li key={i}>{s}</li>)}</ul>}{!!t.blockers.length&&<p className={css.help}>Espera: {t.blockers.join("; ")}</p>}
    <div className={css.meta}><span>{t.owner||"Sin responsable"}</span><span>{t.priority}</span><span>{date(t.due)}</span>{t.order>0&&<span>Paso {t.order}</span>}</div>
    {t.stage==="recurring"&&<p className={css.help}>Recurrente: después de hacerla, bajá su posición. El ranking del proyecto se aplica a sus acciones.</p>}<div className={css.actions}><button className={css.button} disabled={busy||!!error||refreshing} onClick={()=>editTask(t)}>Editar acción</button>{t.stage==="ready"&&<button className={css.primary} disabled={busy||!!error||refreshing} onClick={()=>editTask(t,"doing",true)}>Empezar</button>}{t.stage==="doing"&&<button className={css.primary} disabled={busy||!!error||refreshing} onClick={()=>editTask(t,"done",true)}>Finalizar</button>}{safeDoc(t.doc)&&<a href={safeDoc(t.doc)} target="_blank" rel="noreferrer">Documento ↗</a>}</div>
  </article>;
  if(authLoading)return <main className={css.panel}><div className={css.login}>Verificando acceso…</div></main>;
  if(!sessionEmail)return <main className={css.panel}><div className={`${css.card} ${css.login}`}><span className={css.brand}>Ø UnderTango · privado</span><h1>Panel de control</h1><p>Frentes, acciones y próximos pasos en un solo lugar.</p>{error&&<p className={css.error} role="alert">{error}</p>}<button className={css.primary} disabled={refreshing} onClick={()=>refresh().catch(()=>{})}>{refreshing?"Verificando…":"Volver a intentar"}</button><p className={css.help}>El acceso queda guardado en el navegador habilitado por Pablo.</p><a href="/">Volver al sitio</a></div></main>;
  const counts=(stage:Stage)=>data?.tasks.filter(t=>t.stage===stage).length||0;
  const filtered=data?.tasks.filter(t=>(tab==="all"?!["done","cancelled"].includes(t.stage):tab==="history"?["done","cancelled"].includes(t.stage):t.stage===tab)&&(!taskProject||t.projectIds.includes(taskProject))&&matches([t.name,t.owner,...data.projects.filter(p=>t.projectIds.includes(p.id)).map(p=>p.name)].join(" ")))||[];
  return <main className={css.panel}><header className={css.top}><div><span className={css.brand}>Ø UnderTango · operación</span><h1>Panel de control</h1><div className={css.muted}>{data?`Airtable · última lectura ${new Date(data.updatedAt).toLocaleTimeString("es-AR",{timeZone:"America/Argentina/Cordoba",hour:"2-digit",minute:"2-digit"})}`:"Conectando con Airtable…"}</div></div><div className={css.actions}><button className={css.button} disabled={refreshing||busy} onClick={()=>refresh(true).catch(()=>{})}>{refreshing?"Actualizando…":"Actualizar"}</button><button className={css.primary} disabled={!data||busy||!!error} onClick={()=>newTask()}>+ Capturar acción</button><a className={css.linkButton} href="/">Volver al sitio</a></div></header>
    {error&&<div className={css.error} role="alert">{error}{data&&<div>La información visible corresponde a la última lectura. Actualizá para seguir editando.</div>}</div>}{notice&&<div className={css.notice} role="status">{notice}<button className={css.linkButton} onClick={()=>setNotice("")}>Cerrar aviso</button></div>}
    {data?<><nav className={css.tabs} aria-label="Vistas del panel">{[["fronts","Frentes",data.fronts.length],["doing","En curso",counts("doing")],["waiting","En espera",counts("waiting")],["catalog","Por catalogar",counts("catalog")+data.projectIssues.length],["all","Todas las acciones",data.tasks.filter(t=>!["done","cancelled"].includes(t.stage)).length],["projects","Proyectos",data.projects.filter(p=>p.open).length],["events","Disparadores",data.events.length],["history","Historial",counts("done")+counts("cancelled")]].map(([key,label,count])=><button key={key} className={`${css.tab} ${tab===key?css.active:""}`} aria-current={tab===key?"page":undefined} onClick={()=>{setTab(String(key));setTaskProject("");}}>{label}<span className={css.count}>{count}</span></button>)}</nav>
    {tab==="fronts"?<><p className={css.help}>Cada frente muestra las primeras tres acciones disponibles, ordenadas por ranking del proyecto y paso de la acción. Las esperas y acciones en curso dejan lugar a la siguiente disponible.</p><div className={css.fronts}>{data.fronts.map(front=><section key={front.name} className={css.front}><h2>Frente {front.name}</h2><p className={css.muted}>Disponibles · {front.tasks.length} acciones inmediatas</p><button className={css.button} onClick={()=>openRanking(front.name)}>Ver ranking de {front.name}</button>{front.tasks.map(id=>taskCard(data.tasks.find(t=>t.id===id)!))}{(()=>{
      const unavailable=data.projects.filter(p=>p.open&&p.front===front.name&&Number.isInteger(p.rank)&&p.rank>=1&&!projectActionSummary(p.id,data.tasks).ready).sort((a,b)=>a.rank-b.rank);
      return unavailable.length?<details className={css.frontAttention} open={!front.tasks.length}><summary>{unavailable.length} {unavailable.length===1?"proyecto sin acción inmediata":"proyectos sin acción inmediata"}</summary>{unavailable.map(p=>{const summary=projectActionSummary(p.id,data.tasks);return <div className={css.unavailableProject} key={p.id}><strong>{frontPosition(p.front,p.rank)} · {p.name}</strong><p>{summary.text}</p>{summary.issues.map(issue=><p className={css.issueText} key={issue}>{issue}</p>)}<button className={css.button} onClick={()=>summary.open?openProjectTasks(p.id):newTask(p.id)} disabled={busy||refreshing||!!error}>{summary.open?"Ver acciones":"Definir próxima acción"}</button></div>;})}</details>:!front.tasks.length?<div className={css.empty}><strong>Sin acciones disponibles en este frente</strong>Revisá sus estados y dependencias desde el ranking.</div>:null;
    })()}</section>)}</div></>:<>{taskProject&&<div className={css.projectFilter}><strong>Acciones de {data.projects.find(p=>p.id===taskProject)?.name}</strong><button className={css.linkButton} onClick={()=>setTaskProject("")}>Ver todas las acciones</button></div>}<div className={css.toolbar}><input className={css.search} aria-label="Buscar en esta vista" placeholder="Buscar por acción, proyecto o responsable…" value={search} onChange={e=>setSearch(e.target.value)}/>{tab==="projects"&&<label className={css.rankingFilter}>Frente<select aria-label="Filtrar ranking por frente" value={projectFront} onChange={e=>setProjectFront(e.target.value)}><option value="">Todos</option>{FRONTS.map(front=><option key={front}>{front}</option>)}</select></label>}{tab==="events"&&<button className={css.primary} disabled={!!error} onClick={()=>editEvent()}>+ Registrar lo que espero</button>}</div>
    {tab==="projects"?<>{data.projects.filter(p=>p.open&&(!projectFront||p.front===projectFront)&&matches(p.name)).sort((a,b)=>a.front.localeCompare(b.front)||a.rank-b.rank).map(p=>{const summary=projectActionSummary(p.id,data.tasks);return <article className={css.projectRow} key={p.id}><div><span className={css.muted}>{frontPosition(p.front,p.rank)} · {p.front} · {data.fronts.some(f=>f.tasks.some(id=>data.tasks.find(t=>t.id===id)?.projectIds.includes(p.id)))?"Con acción visible":"En la cola"}</span><h3>{p.name}</h3><p className={css.help}>{data.tasks.filter(t=>t.projectIds.includes(p.id)&&!["done","cancelled"].includes(t.stage)).length} acciones abiertas · {p.status}</p><p className={summary.ready?css.help:css.issueText}>{summary.text}</p></div><div className={css.actions}><button className={css.button} onClick={()=>openProjectTasks(p.id)}>Ver acciones</button><button className={css.button} disabled={!!error||refreshing} onClick={()=>editProject(p.id,true)}>Frente y posición</button><button className={css.button} disabled={!!error} onClick={()=>editProject(p.id)}>Editar proyecto</button><button className={css.button} disabled={!!error} onClick={()=>newTask(p.id)}>+ Próximo paso</button>{safeDoc(p.doc)&&<a href={safeDoc(p.doc)} target="_blank" rel="noreferrer">Documento ↗</a>}</div></article>;})}</>:tab==="events"?<div className={css.list}>{data.events.filter(e=>matches(e.name)).map(e=><article className={css.card} key={e.id}><span className={css.badge}>{e.status} · {e.type}</span><h3>{e.name}</h3><p className={css.help}>{data.tasks.filter(t=>t.eventIds.includes(e.id)&&!["done","cancelled"].includes(t.stage)).length} acciones vinculadas</p>{e.evidence&&<p>{e.evidence}</p>}<button className={css.button} disabled={!!error} onClick={()=>editEvent(e.id)}>Abrir / confirmar hecho</button></article>)}{!data.events.length&&<div className={css.empty}>Todavía no hay hechos registrados.</div>}</div>:<>
    {tab==="catalog"&&<><p className={css.help}>Cada registro explica qué falta. Definilo, vinculalo o descartalo con un motivo. Los proyectos sin próximo paso también aparecen aquí.</p>{data.projectIssues.filter(item=>matches(data.projects.find(p=>p.id===item.id)!.name)).map(item=>{const p=data.projects.find(p=>p.id===item.id)!;return <article className={css.projectRow} key={item.id}><div><span className={css.badge}>Proyecto por revisar</span><h3>{p.name}</h3><p className={css.help}>{item.reasons.join(" · ")}</p></div><div className={css.actions}><button className={css.button} disabled={!!error} onClick={()=>editProject(p.id)}>Revisar proyecto</button><button className={css.button} disabled={!!error} onClick={()=>newTask(p.id)}>Definir próximo paso</button></div></article>;})}<h2 className={css.sectionTitle}>Acciones por catalogar</h2></>}
    <div className={css.list}>{filtered.slice(0,limit).map(taskCard)}</div>{!filtered.length&&<div className={css.empty}>No hay acciones que coincidan con esta vista y búsqueda.</div>}{filtered.length>limit&&<div className={css.pagination}><button className={css.button} onClick={()=>setLimit(n=>n+36)}>Mostrar más ({filtered.length-limit} restantes)</button></div>}</>}</>}
    </>:!error&&<div className={css.empty}>Leyendo los frentes y sus acciones…</div>}
    {editor&&data&&(editor.mode?<QuickForm key={`${editor.mode}-${editor.id}`} editor={editor} data={data} busy={busy} onClose={()=>setEditor(undefined)} onSave={save} onCreateEvent={createWaitEvent}/>:<EditForm key={`${editor.kind}-${editor.id||"new"}`} editor={editor} data={data} busy={busy} onClose={()=>setEditor(undefined)} onSave={save}/>)}
  </main>;
}
function QuickForm({editor,data,busy,onClose,onSave,onCreateEvent}:{editor:Editor;data:Data;busy:boolean;onClose:()=>void;onSave:(changes:Record<string,any>)=>Promise<void>;onCreateEvent:(name:string)=>Promise<string>}){
  const position=editor.mode==="position",task=data.tasks.find(t=>t.id===editor.id),project=data.projects.find(p=>p.id===editor.id);
  const [front,setFront]=useState(editor.initial.front||FRONTS[0]),[rank,setRank]=useState<number|string>(editor.initial.rank||1);
  const [stage,setStage]=useState<Stage>(editor.initial.stage||"ready"),[reason,setReason]=useState(editor.initial.reason||""),[evidence,setEvidence]=useState("");
  const [dependencies,setDependencies]=useState<string[]>(editor.initial.dependencies||[]),[events,setEvents]=useState<string[]>(editor.initial.events||[]);
  const [newEvent,setNewEvent]=useState(""),[creating,setCreating]=useState(false),[error,setError]=useState("");
  const actionSummary=project?projectActionSummary(project.id,data.tasks):undefined;
  const maxRank=data.projects.filter(p=>p.open&&p.id!==project?.id&&p.front===front).length+1;
  const rankValid=Number.isInteger(Number(rank))&&Number(rank)>=1&&Number(rank)<=maxRank;
  const linked=dependencies.length+events.length>0;
  const pending=dependencies.some(id=>{const t=data.tasks.find(t=>t.id===id);return t&&!["done","cancelled"].includes(t.stage);})||events.some(id=>{const event=data.events.find(e=>e.id===id);return event&&event.status!=="Descartado"&&(event.status!=="Ocurrido"||!event.occurred||!event.evidence.trim());});
  const needsEvidence=stage==="done"||stage==="cancelled";
  const unchanged=position?front===project?.front&&Number(rank)===project?.rank:stage===task?.stage&&reason===editor.initial.reason&&JSON.stringify(dependencies)===JSON.stringify(editor.initial.dependencies)&&JSON.stringify(events)===JSON.stringify(editor.initial.events)&&!evidence;
  const blocked=busy||creating||unchanged||(position?!rankValid:stage==="waiting"?(!linked||!pending):needsEvidence?!evidence.trim():false);
  const destination:Record<Stage,string>={recurring:"Permanece abierta. Después de hacerla, bajá su posición en el ranking para dar lugar a otras acciones. Sin fecha automática ni cierre definitivo.",ready:"Se mostrará si está entre las primeras tres acciones disponibles del frente, según el ranking.",doing:"Saldrá de Frentes y quedará en En curso.",waiting:"Saldrá de Frentes cuando guardes una dependencia válida. Volverá a estar disponible cuando se confirme que todo lo vinculado se resolvió.",catalog:"Saldrá de Frentes y quedará en Por catalogar hasta que la revises.",done:"Saldrá de Frentes y quedará en Historial con su resultado.",cancelled:"Saldrá de Frentes y quedará en Historial con el motivo del descarte."};
  async function submit(event:FormEvent){
    event.preventDefault();if(blocked)return;setError("");
    const changes:Record<string,any>=position?{front,rank:Number(rank)}:{stage};
    if(!position){
      if(["waiting","catalog"].includes(stage))changes.reason=reason.trim();
      changes.dependencies=dependencies;changes.events=events;
      if(needsEvidence)changes.evidence=evidence.trim();
    }
    try{await onSave(changes);}catch(error){setError(error instanceof Error?error.message:"No se pudo guardar. La acción conserva su estado anterior.");}
  }
  async function createEvent(){
    if(!newEvent.trim()||creating)return;setCreating(true);setError("");
    try{const id=await onCreateEvent(newEvent.trim());setEvents(ids=>[...new Set([...ids,id])]);setNewEvent("");}
    catch(error){setError(error instanceof Error?error.message:"No se pudo registrar el hecho. Revisá la lista antes de reintentar.");}
    finally{setCreating(false);}
  }
  return <Modal onClose={onClose} busy={busy||creating} compact><div className={css.quickHeader}><span className={css.brand}>{position?"Proyecto":"Acción"}</span><button className={css.linkButton} disabled={busy||creating} onClick={onClose}>Cerrar</button></div>
    <h2 id="editor-heading">{position?"Frente y posición":"Cambiar estado"}</h2><p className={css.quickName}>{position?project?.name:task?.name}</p>
    <form onSubmit={submit}>
      {position?<><div className={css.positionPreview}>{rankValid?frontPosition(front,Number(rank)):"Elegí una posición"}</div><div className={css.two}><div><label htmlFor="quick-front">Frente del proyecto</label><select id="quick-front" value={front} disabled={busy} onChange={event=>{setFront(event.target.value);setRank(1);setError("");}}>{FRONTS.map((name,i)=><option key={name} value={name}>{i+1} · {name}</option>)}</select></div><div><label htmlFor="quick-rank">Posición</label><input id="quick-rank" type="number" min={1} max={maxRank} step={1} required value={rank} disabled={busy} onChange={event=>{setRank(event.target.value);setError("");}}/></div></div><p className={css.help}>Elegí del 1 al {maxRank}. El proyecto se insertará en esa posición y el resto conservará su orden. El cambio se aplica a todas sus acciones. Frentes toma las primeras tres disponibles del ranking completo.</p>{actionSummary&&!actionSummary.ready&&<div className={css.rankWarning} role="status"><strong>Mover el proyecto no habilita sus acciones.</strong><p>{actionSummary.text}</p>{actionSummary.issues.map(issue=><p key={issue}>{issue}</p>)}<p>Después de guardar, abrí Ver acciones y revisá su estado.</p></div>}</>:<>
        <label htmlFor="quick-stage">Estado de la acción</label><select id="quick-stage" value={stage} disabled={busy||creating} onChange={event=>{setStage(event.target.value as Stage);setError("");}}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><p className={css.help}>{destination[stage]}</p>
        {(stage==="waiting"||linked)&&<div className={css.waitFields}><p className={css.help}><strong>Vinculá al menos una acción pendiente o un hecho que deba ocurrir.</strong> Si vinculás varios, deben resolverse todos. Para liberar esta acción, quitá los vínculos que ya no correspondan y elegí Acción inmediata.</p>
          <Choices label="Acciones que deben terminar" options={data.tasks.filter(t=>t.id!==task?.id&&(t.stage!=="cancelled"||dependencies.includes(t.id))).map(t=>({id:t.id,name:`${labels[t.stage]} · ${t.name}`}))} value={dependencies} onChange={ids=>{setDependencies(ids);if(stage==="waiting"&&!ids.length&&!events.length)setStage("ready");setError("");}}/>
          <Choices label="Hechos que deben ocurrir" options={data.events.map(event=>({id:event.id,name:`${event.status} · ${event.name}`}))} value={events} onChange={ids=>{setEvents(ids);if(stage==="waiting"&&!ids.length&&!dependencies.length)setStage("ready");setError("");}}/>
          {!linked?<p className={css.help} role="status">Falta un vínculo: todavía no se puede guardar En espera.</p>:!pending&&<p className={css.help} role="status">No hay una dependencia pendiente válida. Elegí otra o conservá Acción inmediata.</p>}
          <details><summary>Crear un hecho que todavía no existe</summary><label htmlFor="new-wait-event">Qué tiene que suceder</label><input id="new-wait-event" maxLength={250} placeholder="Ej.: recibir la confirmación del hotel" value={newEvent} disabled={creating||busy} onChange={event=>setNewEvent(event.target.value)}/><button type="button" className={css.button} disabled={creating||busy||!newEvent.trim()} onClick={createEvent}>{creating?"Registrando…":"Crear hecho y seleccionarlo"}</button><p className={css.help}>El hecho se registra en Disparadores. Guardá el estado para vincularlo a esta acción.</p></details>
        </div>}
        {["waiting","catalog"].includes(stage)&&<><label htmlFor="quick-reason">{stage==="waiting"?"Contexto de la espera (opcional)":"Qué queda por revisar (opcional)"}</label><textarea id="quick-reason" maxLength={1000} value={reason} disabled={busy||creating} onChange={event=>setReason(event.target.value)}/></>}
        {needsEvidence&&<><label htmlFor="quick-evidence">{stage==="done"?"Resultado que confirma el cierre":"Motivo del descarte"}</label><textarea id="quick-evidence" maxLength={1500} required value={evidence} disabled={busy} onChange={event=>setEvidence(event.target.value)}/></>}
      </>}
      {error&&<p className={css.error} role="alert">{error}</p>}<footer><button type="button" className={css.button} disabled={busy||creating} onClick={onClose}>Cancelar</button><button className={css.primary} disabled={blocked}>{busy?"Guardando y verificando…":position?"Guardar posición":"Guardar estado"}</button></footer>
    </form>
  </Modal>;
}
function EditForm({editor,data,busy,onClose,onSave}:{editor:Editor;data:Data;busy:boolean;onClose:()=>void;onSave:(changes:Record<string,any>)=>Promise<void>}){
  const [value,setValue]=useState(editor.initial),[error,setError]=useState("");const set=(key:string,v:any)=>setValue(old=>({...old,[key]:v}));
  async function submit(e:FormEvent){e.preventDefault();setError("");const change=Object.fromEntries(Object.entries(value).filter(([k,v])=>!k.startsWith("_")&&(!editor.id||JSON.stringify(v)!==JSON.stringify(editor.initial[k]))));if(editor.initial._previousStage)change.stage=value.stage;try{await onSave(change);}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar.");}}
  const task=editor.kind==="task"?data.tasks.find(t=>t.id===editor.id):undefined;
  const input=(key:string,label:string,type="text",max=250)=><div><label htmlFor={`edit-${key}`}>{label}</label><input id={`edit-${key}`} type={type} maxLength={max} value={value[key]??""} onChange={e=>set(key,type==="number"?Number(e.target.value):e.target.value)}/></div>;
  const select=(key:string,label:string,options:string[])=><div><label htmlFor={`edit-${key}`}>{label}</label><select id={`edit-${key}`} value={value[key]} onChange={e=>set(key,e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></div>;
  const area=(key:string,label:string,required=false)=><div><label htmlFor={`edit-${key}`}>{label}</label><textarea id={`edit-${key}`} required={required} maxLength={key==="reason"?1000:1500} value={value[key]||""} onChange={e=>set(key,e.target.value)}/></div>;
  return <Modal onClose={onClose} busy={busy}><div className={css.actions}><span className={css.brand}>{editor.kind==="task"?"Acción":editor.kind==="project"?"Proyecto":"Hecho esperado"}</span><button className={css.linkButton} disabled={busy} onClick={onClose}>Cerrar</button></div><h2 id="editor-heading">{editor.id?editor.kind==="project"?data.projects.find(p=>p.id===editor.id)?.name:value.name:editor.kind==="task"?"Capturar próximo paso":"Registrar lo que espero"}</h2><form onSubmit={submit}>
    {editor.kind!=="project"&&input("name",editor.kind==="task"?"Acción concreta":"Hecho que debe ocurrir")}
    {editor.kind==="task"&&<><label htmlFor="edit-stage">Estado de la acción</label><select id="edit-stage" value={value.stage} onChange={e=>set("stage",e.target.value)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{task?.description&&<details><summary>Descripción registrada</summary><p className={css.help}>{task.description}</p></details>}<div className={css.two}>{input("owner","Responsable")}{input("due","Vencimiento","date")}</div><div className={css.two}>{select("priority","Prioridad",["Alta","Media","Baja"])}{input("order","Paso en el plan","number")}</div>
    {["waiting","catalog"].includes(value.stage)&&area("reason","Qué falta o por qué espera")}{["done","cancelled"].includes(value.stage)&&area("evidence",value.stage==="done"?"Resultado que confirma el cierre":"Motivo del descarte",true)}
    <Choices label="Proyectos vinculados" options={data.projects.map(p=>({id:p.id,name:p.name+(p.open?"":" · cerrado")}))} value={value.projects} onChange={v=>set("projects",v)}/>
    <details open={value.stage==="waiting"}><summary>Dependencias y hechos esperados</summary><p className={css.help}>Todas las dependencias deben estar resueltas. Una explicación sola no habilita En espera. Registrá hechos externos en Disparadores y luego vinculalos aquí.</p><Choices label="Depende de acciones" options={data.tasks.filter(t=>t.id!==editor.id&&t.stage!=="cancelled").map(t=>({id:t.id,name:`${labels[t.stage]} · ${t.name}`}))} value={value.dependencies} onChange={v=>set("dependencies",v)}/><Choices label="Eventos disparadores" options={data.events.map(e=>({id:e.id,name:`${e.status} · ${e.name}`}))} value={value.events} onChange={v=>set("events",v)}/></details>
    <details><summary>Caso relacionado</summary><Choices label="Casos vinculados" options={data.cases} value={value.cases} onChange={v=>set("cases",v)}/></details></>}
    {editor.kind==="project"&&<><p className={css.help}>La acción actual se obtiene de Seguimientos. Para cerrar el proyecto, resolvé o reasigná sus acciones abiertas.</p><div className={css.two}>{select("front","Frente",["Primario","Secundario","Terciario"])}{input("rank","Posición en el frente","number")}</div>{select("status","Estado del proyecto",["Activo","En espera","Completado","Archivado"])}</>}
    {editor.kind==="event"&&<>{select("type","Tipo de hecho",["Material","Respuesta","Pago","Fecha","Aprobación","Entrega","Disponibilidad","Otro"])}{select("status","Estado del hecho",["Esperando","Ocurrido","Descartado"])}{area("evidence","Evidencia / contexto",value.status==="Ocurrido")}<p className={css.help}>Marcar Ocurrido habilita las acciones vinculadas sin otras dependencias. Una fecha de revisión no demuestra que llegó una respuesta o un pago.</p></>}
    {editor.kind!=="event"&&input("doc","Documento de apoyo en Drive / Docs","url",1000)}
    {editor.id&&<p><a href={`https://airtable.com/${BASE}/${TABLES[editor.kind==="task"?"tasks":editor.kind==="project"?"projects":"events"]}/${editor.id}`} target="_blank" rel="noreferrer">Abrir registro completo en Airtable ↗</a></p>}{error&&<p className={css.error} role="alert">{error}</p>}<footer><button type="button" className={css.button} disabled={busy} onClick={onClose}>Cancelar</button><button className={css.primary} disabled={busy}>{busy?"Guardando y verificando…":"Guardar en Airtable"}</button></footer></form></Modal>;
}
