import type { Metadata } from "next";
import styles from "./tropcalia.module.css";
export const metadata: Metadata = {title:"Rave Triple Frontera · TropCalia",description:"Bailinho Fest na TropCalia: música ao vivo, eletrônica, dança e experiências com o público. Uma proposta Ø UnderTango.",alternates:{canonical:"/tropcalia"},openGraph:{title:"Rave Triple Frontera · TropCalia",description:"Bailinho Fest: música ao vivo, eletrônica e dança. Conheça os três formatos da experiência Ø UnderTango.",url:"https://www.undertangoclub.com/tropcalia",locale:"pt_BR",type:"website",images:[{url:"https://www.undertangoclub.com/tropcalia-social-v2.jpg",width:1200,height:630,type:"image/jpeg",alt:"Rave Triple Frontera · Bailinho Fest · TropCalia"}]},twitter:{card:"summary_large_image",title:"Rave Triple Frontera · TropCalia",description:"Bailinho Fest · Música ao vivo, eletrônica e dança.",images:["https://www.undertangoclub.com/tropcalia-social-v2.jpg"]},robots:{index:false,follow:false}};
const formats = [
 {id:"01",name:"Essencial",label:"O PRIMEIRO ENCONTRO",price:80,min:30,duration:"1 hora",cast:"2 bailarinos",text:"Um casal de tango transforma a noite em descoberta: show, aula e interação, com espaço para todo mundo entrar na dança.",tags:["Casal de tango","Aula + show","Momento bailinho"]},
 {id:"02",name:"Frontera",label:"RECOMENDADO POR CARLOS",price:100,min:50,duration:"1h30",cast:"Casal de tango + saxo + pianista",text:"O ponto de equilíbrio: dança, saxofone e piano ao vivo. Presença de palco, proximidade com o público e uma experiência que termina em encontro.",tags:["4 artistas em cena","Música ao vivo","Show + participação"]},
 {id:"03",name:"Impacto",label:"A EXPERIÊNCIA PREMIUM",price:120,min:60,duration:"1h30",cast:"5 músicos + 4 bailarinos",text:"Tango eletrônico, energia de banda e dança em cena. Um espetáculo que atravessa estilos e abre espaço para viver a noite junto.",tags:["9 artistas em cena","Banda + eletrônica","Show + bailinho"]}
];
export default function TropCaliaPage(){return <main className={styles.page} lang="pt-BR">
 <nav className={styles.nav}><a href="https://www.undertangoclub.com/">Ø UNDERTANGO CLUB</a><span>TROPCALIA · PROPOSTA PARA REVISÃO</span></nav>
 <header className={styles.hero}><p className={styles.eyebrow}>MÚSICA AO VIVO / ELETRÔNICA / DANÇA</p><h1>Rave<br/><em>Triple Frontera.</em></h1><p className={styles.subtitle}>Bailinho Fest</p><p className={styles.lead}>Três fronteiras. Uma pista. Uma noite para assistir, descobrir e dançar — do primeiro passo à energia de um grande espetáculo.</p><a className={styles.button} href="#formatos">Escolha a dimensão da noite ↓</a><div className={styles.strip}><span>Show em todos os formatos</span><span>Interação com o público</span><span>Aula de tango + bailinho</span></div></header>
 <section id="formatos" className={styles.section}><p className={styles.eyebrow}>TRÊS FORMATOS · EXPERIÊNCIA POR PESSOA</p><h2>A noite ganha escala.</h2><p className={styles.intro}>Uma proposta que cresce com as entradas vendidas. O formato e o elenco são confirmados antes da apresentação, conforme o mínimo de vendas e as condições do espaço.</p>
 <div className={styles.grid}>{formats.map(f=><article key={f.id} className={`${styles.card} ${f.id==='02'?styles.featured:''}`}><div className={styles.cardTop}><span>{f.id}</span><span>{f.label}</span></div><h3>{f.name}</h3><p className={styles.description}>{f.text}</p><div className={styles.tags}>{f.tags.map(t=><span key={t}>{t}</span>)}</div><div className={styles.cast}>{f.cast}<small>{f.duration} · possibilidade de extensão a combinar</small></div><div className={styles.price}><span>PREÇO PROPOSTO</span><strong>R$ {f.price}<small>por pessoa</small></strong></div><div className={styles.minimum}><strong>{f.min} pessoas</strong><span>mínimo de ativação proposto</span></div><p className={styles.total}>R$ {(f.price*f.min).toLocaleString('pt-BR')} em entradas no mínimo proposto</p></article>)}</div>
 <p className={styles.note}>Valores e mínimos sujeitos à validação dos custos finais. Extensões de duração são combinadas previamente; não estão incluídas automaticamente.</p></section>
 <section className={styles.section}><p className={styles.eyebrow}>UMA EXPERIÊNCIA COMPLETA</p><h2>Do palco para a pista.</h2><div className={styles.steps}><div><b>01 / ASSISTIR</b><h3>O show abre a noite.</h3><p>Dança e presença cênica em todos os formatos. Música ao vivo e eletrônica conforme a formação escolhida.</p></div><div><b>02 / EXPERIMENTAR</b><h3>O público faz parte.</h3><p>Interação e aula de tango para descobrir o ritmo. Não é necessário saber dançar.</p></div><div><b>03 / DANÇAR</b><h3>É hora do bailinho.</h3><p>Um momento para sair da cadeira e viver a experiência. A programação se adapta ao grupo e à duração combinada.</p></div></div></section>
 <section className={styles.venue}><div><p className={styles.eyebrow}>TROPCALIA</p><h2>O espaço encontra<br/>o espetáculo.</h2><p>Segundo Carlos, a casa tem três ambientes e um deles acomoda até 180 pessoas sentadas. O palco comporta até 10 músicos, conforme informado pelo local.</p></div><div className={styles.tech}><h3>Técnica a cargo da TropCalia</h3><p>Luz e som fornecidos pelo local, conforme informado por Carlos. A disponibilidade de tela ainda será confirmada.</p><p>A montagem deve preservar a área de dança, a circulação e a capacidade efetiva de público. O elenco máximo desta proposta é de 5 músicos e 4 bailarinos.</p></div></section>
 <section className={styles.section}><p className={styles.eyebrow}>CONDIÇÕES DA PARCERIA</p><h2>Uma base clara para começar.</h2><div className={styles.steps}><div><h3>Bilheteria UnderTango</h3><p>TropCalia: alimentos e bebidas. UnderTango: ingressos.</p></div><div><h3>Ativação por vendas</h3><p>Os mínimos propostos consideram ingressos pagos pelo valor integral. Taxas, impostos, descontos e demais custos precisam ser fechados antes da confirmação.</p></div><div><h3>Condições a combinar</h3><p>Alimentos e bebidas ficam a cargo da TropCalia. Traslados, canais de venda e extensões de horário são combinados separadamente.</p></div></div></section>
 <footer className={styles.footer}><p className={styles.eyebrow}>COMEÇAR PELO EQUILÍBRIO</p><h2>Frontera.<br/>A primeira noite pode ser esta.</h2><p>Casal de tango, saxofone e piano. 1h30 de experiência.<br/>R$100 por pessoa · 50 entradas como mínimo proposto.</p><a className={styles.button} href={'https://wa.me/5493757618270?text='+encodeURIComponent('Olá! Vamos conversar sobre Rave Triple Frontera na TropCalia e o formato Frontera.')} target="_blank" rel="noopener noreferrer">Conversar com a UnderTango ↗</a><small>Ø UnderTango Club × TropCalia · Proposta para revisão · Sujeita a disponibilidade e acordo.</small></footer>
 <section className={styles.section} aria-labelledby="reparto"><p className={styles.eyebrow}>TRANSPARÊNCIA · RECEITA DOS INGRESSOS</p><h2 id="reparto">Como a UnderTango distribui a bilheteria.</h2><p className={styles.intro}>A receita de alimentos e bebidas pertence à TropCalia. O diagrama abaixo mostra somente a distribuição interna da receita dos ingressos da UnderTango.</p>
 <h3>Essencial e Frontera</h3><div className={styles.flowRoot}>INGRESSOS · 100%</div><div className={styles.flowArrow} aria-hidden="true">↓</div>
 <div className={styles.splitBar} role="img" aria-label="Artistas 41,5%; Carlos 8,5%; produção e logística 25%; UnderTango 25%"><span style={{flex:41.5,background:'#dfbc81'}}/><span style={{flex:8.5,background:'#db8096'}}/><span style={{flex:25,background:'#8baea5'}}/><span style={{flex:25,background:'#a699c5'}}/></div>
 <div className={styles.splitGrid}>{[['41,5%','Artistas','Honorários do elenco'],['8,5%','Carlos','Representação e articulação local'],['25%','Produção e logística','Orçamento operacional'],['25%','UnderTango','Parcela da organização']].map(([pct,name,detail])=><div key={name}><strong>{pct}</strong><h3>{name}</h3><p>{detail}</p></div>)}</div>
 <p className={styles.note}>Os 8,5% de Carlos saem da metade originalmente destinada à parte artística: 50% = 41,5% para artistas + 8,5% para Carlos.</p>
 <h3>Impacto · distribuição Premium</h3><div className={styles.splitBar} role="img" aria-label="Premium: artistas 51,5%; Carlos 8,5%; produção 20%; UnderTango 20%"><span style={{flex:51.5,background:'#dfbc81'}}/><span style={{flex:8.5,background:'#db8096'}}/><span style={{flex:20,background:'#8baea5'}}/><span style={{flex:20,background:'#a699c5'}}/></div><div className={styles.splitGrid}>{[['51,5%','Artistas'],['8,5%','Carlos'],['20%','Produção e logística'],['20%','UnderTango']].map(([pct,name])=><div key={name}><strong>{pct}</strong><h3>{name}</h3></div>)}</div><p className={styles.note}>No Premium, a parcela de artistas aumenta para 51,5%, com 20% para produção e logística e 20% para UnderTango. Carlos mantém 8,5%.</p><h3>Valores nos mínimos propostos</h3><div className={styles.grid}>{formats.map((f,i)=>{const revenue=f.min*f.price;const count=[2,4,9][i];const artistRate=i===2?.515:.415;const otherRate=i===2?.20:.25;const brl=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});return <article key={f.id} className={styles.moneyCard}><h3>{f.name}</h3><p>{f.min} ingressos × {brl(f.price)}</p><strong className={styles.moneyTotal}>{brl(revenue)}</strong><dl><div><dt>Artistas · {i===2?"51,5%":"41,5%"}</dt><dd>{brl(revenue*artistRate)}</dd></div><div><dt>Carlos · 8,5%</dt><dd>{brl(revenue*.085)}</dd></div><div><dt>Produção · {i===2?"20%":"25%"}</dt><dd>{brl(revenue*otherRate)}</dd></div><div><dt>UnderTango · {i===2?"20%":"25%"}</dt><dd>{brl(revenue*otherRate)}</dd></div></dl><p className={styles.perArtist}>{brl(revenue*artistRate/count)} por artista, em divisão igual entre {count} artistas.</p></article>})}</div>
 <p className={styles.note}>Simulação com ingressos pagos pelo valor integral, antes de taxas, impostos e devoluções. A divisão igual entre artistas é uma referência de cálculo; os honorários finais serão acordados. As parcelas de produção e UnderTango não representam lucro líquido garantido.</p>
 </section><footer className={styles.portfolio}><p>Conheça a UnderTango em cena.</p><a href="/galeria">Galeria de apresentações <span aria-hidden="true">↗</span></a></footer></main>}



