import fs from 'node:fs';import assert from 'node:assert/strict';import ts from 'typescript';
const url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const modelUrl=url(compile('src/lib/panel-model.ts'));const m=await import(modelUrl),{F}=m;
const g=await import(url(compile('src/lib/action-groups.ts').replace("'./panel-model'",JSON.stringify(modelUrl))));
const fixture={projects:[{id:'project',fields:{[F.projects.name]:'Proyecto de prueba',[F.projects.status]:'Activo'}}],tasks:[],events:[],cases:[],updatedAt:'2026-09-13T12:00:00Z',rankingMode:'action'};
for(const front of m.FRONTS)for(let i=1;i<=45;i++)fixture.tasks.push({id:front+'-'+i,fields:{[F.tasks.name]:'Acción '+front+' '+i,[F.tasks.projects]:['project'],[F.tasks.status]:'Pendiente',[F.tasks.gate]:'Acción inmediata',[F.tasks.front]:front,[F.tasks.rank]:i}});
const seedIds=['recTXZsiQiOviS9O1','recggFm5MIA3DraG8','rec81GMUGA2TpQJ7S','recVABbR7cYApDiVF','rec6ZnmW0ghfWAkbr'];[41,24,39,10,9].forEach((rank,i)=>{fixture.tasks.find(t=>t.id==='Secundario-'+rank).id=seedIds[i];});
const data=process.env.GROUP_TEST_SOURCE?{...JSON.parse(fs.readFileSync(process.env.GROUP_TEST_SOURCE,'utf8')).snapshot,rankingMode:'action'}:fixture;
const ids=['recTXZsiQiOviS9O1','recggFm5MIA3DraG8','rec81GMUGA2TpQJ7S','recVABbR7cYApDiVF','rec6ZnmW0ghfWAkbr'];
const change={name:'Brasil/Pix',members:ids,front:'Secundario',rank:9};
let count=0;function check(n,fn){fn();console.log('OK',n);count++;}
const grouped=g.applyGroupPlan(data,g.planGroup(data,undefined,change),'test-group');
check('agrupa cinco registros existentes y conserva sus estados, dependencias y recurrencia',()=>{assert.equal(grouped.tasks.length,data.tasks.length+1);for(const id of ids){const original=data.tasks.find(t=>t.id===id),current=grouped.tasks.find(t=>t.id===id);for(const [k,v] of Object.entries(original.fields))if(![F.tasks.front,F.tasks.rank].includes(k))assert.deepEqual(current.fields[k],v);assert.equal(current.fields[F.tasks.group],'test-group');}});
check('un puesto de grupo y ninguno de sus pasos duplicado en frentes',()=>{const b=m.board(grouped);assert.equal(b.tasks.find(t=>t.id==='test-group').rank,9);for(const f of b.fronts){assert.ok(f.tasks.length<=3);assert.ok(f.tasks.every(id=>!ids.includes(id)));}const positions=grouped.tasks.filter(t=>!m.closed(t)&&t.fields[F.tasks.front]);assert.equal(new Set(positions.map(t=>t.fields[F.tasks.front]+':'+t.fields[F.tasks.rank])).size,positions.length);});
check('mover grupo entre frentes conserva orden relativo de las otras unidades',()=>{const moved=g.applyGroupPlan(grouped,g.planGroup(grouped,'test-group',{...change,front:'Primario',rank:1}),'unused');for(const front of m.FRONTS){const order=s=>s.tasks.filter(t=>t.id!=='test-group'&&!m.closed(t)&&!g.isMember(t)&&t.fields[F.tasks.front]===front).sort((a,b)=>a.fields[F.tasks.rank]-b.fields[F.tasks.rank]).map(t=>t.id);assert.deepEqual(order(moved),order(grouped));}assert.equal(m.board(moved).fronts[0].tasks[0],'test-group');});
check('terminar un paso conserva posición y elige siguiente disponible',()=>{const before=m.board(grouped).tasks.find(t=>t.id==='test-group');assert.ok(before.nextId);const after=structuredClone(grouped);const done=after.tasks.find(t=>t.id===before.nextId);done.fields[F.tasks.status]='Hecho';done.fields[F.tasks.gate]='Terminada';const next=m.board(after).tasks.find(t=>t.id==='test-group');assert.notEqual(next.nextId,before.nextId);assert.equal(next.rank,before.rank);});
check('grupo bloqueado no consume cupo y conserva la posición',()=>{const after=structuredClone(grouped);for(const t of after.tasks.filter(t=>ids.includes(t.id)))t.fields[F.tasks.activateAt]='2099-01-01T03:00:00Z';const b=m.board(after);assert.ok(b.fronts.every(f=>!f.tasks.includes('test-group')));assert.equal(b.tasks.find(t=>t.id==='test-group').rank,9);});
check('descanso grupal no cambia estados ni borra una fecha posterior',()=>{const after=structuredClone(grouped);after.tasks.find(t=>t.id==='test-group').fields[F.tasks.activateAt]='2027-01-02T03:00:00Z';after.tasks.find(t=>t.id===ids[0]).fields[F.tasks.activateAt]='2027-01-04T03:00:00Z';const b=m.board(after,Date.parse('2027-01-01T12:00:00Z'));assert.equal(b.tasks.find(t=>t.id===ids[0]).activateAt,'2027-01-04T03:00:00Z');assert.equal(b.tasks.find(t=>t.id===ids[1]).stage,'scheduled');assert.ok(b.fronts.every(f=>!f.tasks.includes('test-group')));});
check('rechaza duplicados, grupos anidados y pertenencia múltiple',()=>{assert.throws(()=>g.planGroup(data,undefined,{...change,members:[ids[0],ids[0]]}));assert.throws(()=>g.planGroup(grouped,undefined,{...change,name:'Otro'}));assert.throws(()=>g.planGroup(grouped,undefined,{...change,name:'Otro',members:['test-group']}));});
check('retirar un paso devuelve posición propia sin duplicarla',()=>{const next=g.applyGroupPlan(grouped,g.planGroup(grouped,'test-group',{...change,members:ids.slice(1)}),'unused');const t=next.tasks.find(t=>t.id===ids[0]);assert.ok(!t.fields[F.tasks.group]);assert.equal(t.fields[F.tasks.front],'Secundario');const ranked=next.tasks.filter(t=>!m.closed(t)&&t.fields[F.tasks.front]);assert.equal(new Set(ranked.map(t=>t.fields[F.tasks.front]+':'+t.fields[F.tasks.rank])).size,ranked.length);});
if(process.env.GROUP_TEST_SOURCE){fs.writeFileSync('../grouped-preview.json',JSON.stringify(grouped));fs.writeFileSync('../group-plan.json',JSON.stringify(g.planGroup(data,undefined,change)));}
console.log(`${count} pruebas de grupos aprobadas`);
