import fs from 'node:fs';import assert from 'node:assert/strict';import {PGlite} from '../../group-test-runtime/node_modules/@electric-sql/pglite/dist/index.js';
const live=JSON.parse(fs.readFileSync('../live-group-source.json','utf8'));
const db=new PGlite();
const fields=live.manifest.fields.filter(f=>f.column&&f.sqlType);
const columns=[...new Map(fields.map(f=>[f.column,f.sqlType])).entries()].map(([col,type])=>`"${col}" ${type}`).join(',');
await db.exec(`create schema operativo;create role anon;create role authenticated;create role service_role;
create table operativo.follow_ups(id text primary key,version bigint default 1,${columns},ranking_frente_abierto text generated always as(case when estado not in ('Hecho','Cancelado') then frente_de_accion end) stored,ranking_posicion_abierta int generated always as(case when estado not in ('Hecho','Cancelado') then posicion_de_accion end) stored,unique(ranking_frente_abierto,ranking_posicion_abierta) deferrable initially deferred);
create table operativo.migration_control(singleton boolean primary key,status text,global_revision bigint);
insert into operativo.migration_control values(true,'active',1);
create table operativo.migration_manifest(target_table text primary key,definition jsonb);
create table operativo.panel_write_fields(table_name text,field_id text,primary key(table_name,field_id));
create table operativo.panel_receipts(request_id uuid primary key,actor text,intent jsonb,result jsonb);
create table operativo.test_audit(id text,actor text);
create function operativo.test_stamp() returns trigger language plpgsql as $$begin update operativo.migration_control set global_revision=global_revision+1;insert into operativo.test_audit values(new.id,current_setting('undertango.actor',true));return new;end $$;
create trigger test_stamp after insert or update on operativo.follow_ups for each row execute function operativo.test_stamp();
create function public.ut_panel_snapshot_v3() returns jsonb language sql as $$select '{"tasks":[]}'::jsonb$$;`);
await db.query('insert into operativo.migration_manifest values($1,$2)',['follow_ups',live.manifest]);
for(const field of live.fields)await db.query('insert into operativo.panel_write_fields values($1,$2)',['follow_ups',field]);
await db.exec(live.apply);await db.exec(live.receipt);await db.exec(live.commit);
for(const row of live.snapshot.tasks){const scalar=fields.filter(f=>row.fields[f.id]!==undefined);await db.query(`insert into operativo.follow_ups(id,${scalar.map(f=>'"'+f.column+'"').join(',')}) values($1,${scalar.map((_,i)=>'$'+(i+2)).join(',')})`,[row.id,...scalar.map(f=>row.fields[f.id])]);}
await db.exec(fs.readFileSync('supabase/migrations/20260913130358_add_action_groups.sql','utf8'));
const revision=async()=>(await db.query('select global_revision::text as r from operativo.migration_control')).rows[0].r;
const call=async(request,patches,rev)=>await db.query('select public.ut_panel_commit_v2($1,$2,$3,$4,$5) as receipt',[request,'group-test',{action:'groups-test'},rev,patches]);
const patches=JSON.parse(fs.readFileSync('../group-plan.json','utf8'));
const request='00000000-0000-4000-8000-000000000001',rev=await revision();
const receipt=(await call(request,patches,rev)).rows[0].receipt;assert.equal(receipt.ok,true);
assert.equal((await db.query('select count(*)::int as n from operativo.follow_ups where grupo_de_accion=$1',[receipt.id])).rows[0].n,5);
assert.equal((await db.query("select count(*)::int as n from operativo.follow_ups where tipo_de_accion='group'")).rows[0].n,1);
assert.deepEqual((await call(request,patches,rev)).rows[0].receipt,receipt);console.log('OK creación atómica, cinco miembros e idempotencia');
const before=await revision();await assert.rejects(()=>call('00000000-0000-4000-8000-000000000002',[{table:'follow_ups',id:receipt.id,create:false,fields:{action_rank:1}}],before));assert.equal(await revision(),before);console.log('OK colisión de ranking revierte todo el cambio');
await assert.rejects(()=>call('00000000-0000-4000-8000-000000000003',patches,rev));console.log('OK revisión obsoleta rechazada');
await assert.rejects(()=>db.exec(`begin;update operativo.follow_ups set grupo_de_accion='recTXZsiQiOviS9O1' where grupo_de_accion='${receipt.id}';set constraints all immediate;commit;`));await db.exec('rollback');console.log('OK rechazo de grupo anidado o padre que es una acción');
for(const role of ['anon','authenticated'])for(const fn of ['ut_panel_snapshot_v4()','ut_panel_commit_v2(uuid,text,jsonb,text,jsonb)'])assert.equal((await db.query('select has_function_privilege($1,$2,\'execute\') as allowed',[role,'public.'+fn])).rows[0].allowed,false);console.log('OK lecturas y escrituras nuevas inaccesibles a roles públicos');
assert.ok((await db.query("select count(*)::int as n from operativo.test_audit where actor='group-test'")).rows[0].n>5);console.log('OK las escrituras atraviesan los disparadores existentes de auditoría y revisión');
await db.close();
