const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,file);
require.extensions['.css']=module=>{module.exports=new Proxy({},{get:(_,key)=>String(key)});};
const {dependencyGroups}=require('../src/lib/panel-dependencies.ts');
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const Dependencies=require('../app/panel-de-control/Dependencies.tsx').default;
const projects=[{id:'p',name:'Secretaría',open:true},{id:'q',name:'Gobernanza',open:true}];
const task=(id,stage='ready',deps=[],ps=['p'])=>({id,name:id,stage,dependencies:deps,projectIds:ps});
const tasks=[task('actual'),task('Lucila'),task('ya terminó','done'),task('descartada','cancelled'),task('directa','ready',['actual']),task('indirecta','ready',['directa']),task('compartida','scheduled',[],['p','q']),task('sin proyecto','waiting',[],[])];
const groups=dependencyGroups(tasks,projects,'actual');
assert.deepEqual(groups[0].items.map(t=>t.id),['Lucila','compartida']);
assert.equal(groups[1].items[0].id,'compartida');
assert.equal(groups[2].items[0].id,'sin proyecto');
assert.equal(dependencyGroups(tasks,projects,'actual','Secretaría')[0].items.length,2);
assert.equal(dependencyGroups(tasks,projects,'actual','no existe').length,0);
const selected=['ya terminó','Lucila'];
const html=renderToStaticMarkup(React.createElement(Dependencies,{data:{projects,tasks,events:[{id:'e',name:'Confirmación externa',status:'Esperando'}]},taskId:'actual',dependencies:selected,events:['e'],disabled:false,onChange(){},onBusy(){},async onCreateProject(){return 'p';},async onCreateTask(){return 't';},async onCreateEvent(){return 'e';}}));
assert.match(html,/Qué falta para poder empezar/);
assert.match(html,/✓ Finalizada/);
assert.doesNotMatch(html,/<span>ya terminó<\/span>/);
assert.match(html,/Seleccionadas: 3/);
assert.match(html,/Crear proyecto y elegirlo/);
assert.match(html,/Crear acción y seleccionarla/);
assert.match(html,/Confirmación externa/);
assert.deepEqual(selected,['ya terminó','Lucila']);
console.log('OK: 12 comprobaciones de agrupación, búsqueda, ciclos, finalizadas, selecciones e interfaz.');
