const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const ts = require('typescript');
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
function load(relative, replacements = {}) {
  const filename = path.resolve(__dirname, relative);
  const mod = new Module(filename, module);
  mod.filename = filename; mod.paths = Module._nodeModulePaths(path.dirname(filename));
  const originalRequire = mod.require.bind(mod);
  mod.require = id => id in replacements ? replacements[id] : originalRequire(id);
  const source = fs.readFileSync(filename, 'utf8').replace('function EditForm(', 'export function EditForm(');
  mod._compile(ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, jsx: ts.JsxEmit.ReactJSX } }).outputText, filename);
  return mod.exports;
}
const model = load('../src/lib/panel-model.ts');
const grouping = load('../src/lib/panel-dependencies.ts');
const dependencies = load('../app/panel-de-control/Dependencies.tsx', {'../../src/lib/panel-model':model,'../../src/lib/panel-dependencies':grouping,'./panel.module.css':{default:{}}});
const projectGroups = load('../src/lib/panel-project-groups.ts');
const frontProjects = load('../app/panel-de-control/FrontProjects.tsx', {'../../src/lib/panel-model':model,'../../src/lib/panel-project-groups':projectGroups,'./panel.module.css':{default:{}}});
const { EditForm } = load('../app/panel-de-control/Panel.tsx', { '../../src/lib/panel-model': model, './Dependencies': dependencies, './FrontProjects':frontProjects, './panel.module.css': {default:{}} });
const data = { rankingMode:'action',source:'supabase',projects:[],tasks:[],events:[],cases:[] };
const render = (editor, extra = {}) => renderToStaticMarkup(React.createElement(EditForm, { editor, data, busy:false, onClose(){}, async onSave(){}, async onCreateProject(){return 'p';}, ...extra }));
const project = render({kind:'project',initial:{name:'Proyecto nuevo',purpose:'Resultado',status:'Activo',doc:''}});
assert.match(project, /Crear proyecto/); assert.match(project, /Nombre del proyecto/);
assert.match(project, /Propósito/); assert.doesNotMatch(project, /Posición en el frente/);
assert.doesNotMatch(project, /option[^>]*>Archivado/);
const task = render({kind:'task',initial:{name:'Borrador intacto',stage:'catalog',projects:[],cases:[],dependencies:[],events:[]}});
assert.match(task, /Borrador intacto/); assert.match(task, /Crear proyecto y seleccionarlo/);
assert.match(task, /Proyectos vinculados/); assert.match(task, /la acción se guarda por separado/);
const readOnly = render({kind:'project',initial:{name:'Prueba',status:'Activo'}},{data:{...data,readOnly:true}});
assert.match(readOnly, /fieldset disabled/);
const contextual = render({kind:'task',id:'action',initial:{name:'Pagar factura',stage:'ready',order:21,projects:['independent'],cases:['case'],dependencies:[],events:[]}}, {data:{...data,projects:[{id:'independent',name:'Tareas independientes',open:true},{id:'inherited',name:'Proyecto del caso',open:true}],cases:[{id:'case',name:'Caso',projectIds:['inherited']} ]}});
assert.ok(contextual.indexOf('Tareas independientes') < contextual.indexOf('Acción concreta'));
assert.ok(contextual.indexOf('Proyecto del caso') < contextual.indexOf('Acción concreta'));
assert.doesNotMatch(contextual, /Paso en el plan|id="edit-order"/);
assert.match(contextual, /Número registrado: 21/);
assert.match(contextual, /<details><summary>Referencia de orden anterior/);
assert.match(task, /Sin proyecto vinculado/);
console.log('Project/action rendering checks passed: context, inherited links, empty state and historical order');
