import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const source=ts.transpileModule(fs.readFileSync('src/lib/panel-model.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {F,board,classify,finishTodayChanges,nextAvailableDay}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const row=(id,mask,extra={})=>({id,fields:{[F.tasks.name]:id,[F.tasks.projects]:['p'],[F.tasks.front]:'Secundario',[F.tasks.rank]:Number(id)||1,[F.tasks.status]:'Pendiente',[F.tasks.gate]:'Acción inmediata',...(mask===undefined?{}:{[F.tasks.weekdays]:mask}),...extra}});
const snapshot=tasks=>({rankingMode:'action',updatedAt:'',projects:[{id:'p',fields:{[F.projects.name]:'Proyecto',[F.projects.status]:'Activo'}}],tasks,events:[],cases:[]});
const before=Date.parse('2026-09-14T02:59:59Z'),monday=Date.parse('2026-09-14T03:00:00Z'),tuesday=Date.parse('2026-09-15T15:00:00Z');
const mon=row('1',1),data=snapshot([mon,row('2'),row('3'),row('4')]);
assert.equal(classify(mon,data,before).stage,'scheduled');
assert.equal(classify(mon,data,before).nextAvailableAt,'2026-09-14T03:00:00.000Z');
assert.equal(classify(mon,data,monday).stage,'ready');
assert.deepEqual(board(data,tuesday).fronts[1].tasks,['2','3','4']);
assert.equal(board(data,tuesday).tasks.find(t=>t.id==='1').rank,1);
assert.deepEqual(board(data,monday).fronts[1].tasks,['1','2','3']);
assert.equal(classify(row('1',1,{[F.tasks.status]:'Hecho'}),data,tuesday).stage,'done');
const delayed=row('1',1,{[F.tasks.activateAt]:'2026-09-15T15:00:00Z'});
assert.equal(classify(delayed,snapshot([delayed]),monday).nextAvailableAt,'2026-09-21T03:00:00.000Z');
const rested={...mon,fields:{...mon.fields,[F.tasks.activateAt]:finishTodayChanges(mon,data,monday).activateAt}};
assert.equal(classify(rested,snapshot([rested]),monday).nextAvailableAt,'2026-09-21T03:00:00.000Z');
const waiting=row('1',1,{[F.tasks.status]:'En espera',[F.tasks.gate]:'En espera',[F.tasks.dependencies]:['2']});
assert.equal(classify(waiting,snapshot([waiting,row('2')]),monday).stage,'waiting');
for(const invalid of [0,128,1.5,'1']) assert.equal(classify(row('1',invalid),data,monday).stage,'catalog');
assert.equal(nextAvailableDay(1,NaN).toString(),'NaN');
const group=row('1',1,{[F.tasks.kind]:'group'}),member=row('2',127,{[F.tasks.group]:'1',[F.tasks.groupOrder]:1,[F.tasks.front]:null,[F.tasks.rank]:null});
const grouped=board(snapshot([group,member]),tuesday);
assert.equal(grouped.tasks.find(t=>t.id==='1').stage,'scheduled');
assert.equal(grouped.tasks.find(t=>t.id==='2').stage,'scheduled');
const conflict={...member,fields:{...member.fields,[F.tasks.weekdays]:2}};
assert.match(classify(conflict,snapshot([group,conflict]),monday).issues.join(' '),/no coinciden/);
const everydayGroup={...group,fields:{...group.fields,[F.tasks.weekdays]:127}};
const monMember={...member,fields:{...member.fields,[F.tasks.weekdays]:1}};
assert.equal(board(snapshot([everydayGroup,monMember]),tuesday).tasks.find(t=>t.id==='1').stage,'scheduled');
console.log('Weekday checks passed: Argentine midnight, ranking replacement, defaults, closure, activation, daily rest, dependencies, groups and invalid days.');
